// Generated by CoffeeScript 1.12.7
(function() {
  var Hs, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Hs || (root.Hs = {});

  Hs = root.Hs;

  $(function() {
    return $(window).on("load", function(evt) {
      console.log("chrome plugin load");
      return setTimeout(function() {
        if (window.location.href.indexOf("https://pgy.xiaohongshu.com/solar/advertiser/kol/") > -1) {
          console.log(window.location.href.split("https://pgy.xiaohongshu.com/solar/advertiser/kol/"));
          console.log($("[data-v-7efc0192]").html());
          return console.log($(".noteData[data-v-4bab4de6]").html());
        }
      }, 5000);
    });
  });

}).call(this);


if ($(".request_console_area").length==0){
    $("body").append("<div class=\"request_console_area\" style=\"z-index: 9999;position:fixed;left:0px;top:0px;padding:10px;background:white;box-shadow:0px 4px 8px rgba(0,0,0,0.3);\"><button class=\"fensihuoyuedu\">获取粉丝活跃度</button></div>")
}

// $("body").on("click",".fensihuoyuedu",function(e){
//   chrome.runtime.sendMessage({
//     info: "fensihuoyuedu"
//   }, res => {
//     // 答复
//     // alert(res)
//   })
// })

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) { 
    console.log("==== 数据监听 is_get request ====")
    console.log(request)
    if(request.is_get_num == 0){
      $(".request_console_area").append("<div>"+request.data["data"]["distributions"][2]["description"]+"</div>")
    }else if (request.is_get_num==2){
            $.ajax({
                headers: {
                    Accept: "application/json, text/plain, */*",
                    apiVersion: "2.0",
                    Appkey: 850226,
                    channel: "pc",
                    language: "zh-CN",
                    subsiteId: "10",
                },
                url:request.url,
                type:"GET",
                dataType:"json",
                data:null,
                success:function(data){
                    console.log(data);
                    dom=document.createElement("div");
                    dom.id="wlb_cover";
                    dom.style.position="fixed";
                    dom.style.top="0px";
                    dom.style.right="0px";
                    dom.innerHTML="<textarea id=\"wlb_cover_textarea\" style=\"height:100px;width:200px;\">"+JSON.stringify(data["items"])+"</textarea>";
                    document.body.append(dom);
                },
                error:function(data){}
            })
    }
}); 


