import pyautogui
import os
from stores import store_list
import time
nums = len(store_list)
start_num = 25
for num in range(start_num,nums):
    print("doing:",num)
    pyautogui.moveTo(x=202,y=46)
    pyautogui.click(x=202,y=46)
    time.sleep(2)
    pyautogui.moveTo(x=455,y=83)
    pyautogui.click(x=455,y=83)
    pyautogui.click(x=455,y=83)
    pyautogui.click(x=455,y=83)
    pyautogui.typewrite(store_list[num]["link"])
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.moveTo(x=577,y=115)
    pyautogui.click(x=577,y=115)
    pyautogui.click(x=456,y=143)
    time.sleep(1)
    pyautogui.click(x=577,y=115)
    time.sleep(1)
    pyautogui.hotkey("up")
    pyautogui.press("enter")
    time.sleep(2)
    pyautogui.moveTo(x=350,y=116)
    time.sleep(1)
    pyautogui.click(x=350,y=116,clicks=1)
    time.sleep(1)
    pyautogui.click(x=350,y=116,clicks=1)
    #pyautogui.moveTo(x=action.get("x",None), y=action.get("y",None),duration=0, tween=pyautogui.linear)
    #pyautogui.click(x=action.get("x",None), y=action.get("y",None),clicks=1, button='left')
    pyautogui.hotkey("command","a")
    time.sleep(1)
    pyautogui.hotkey("command","c")
    time.sleep(1)
    pyautogui.moveTo(x=442,y=55)
    pyautogui.click(x=442,y=55)
    time.sleep(2)
    pyautogui.click(x=227,y=168)
    pyautogui.hotkey("command","v")
    time.sleep(2)
    pyautogui.click(x=341,y=233)
    print("done:",num)
    time.sleep(2)
    num +=1

